version: '3.2'

services:
  tabletop-tales:
    image: ghcr.io/jjemus/tabletop_tales:latest

    networks:
      - traefik
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.services.tabletoptales_svc.loadbalancer.server.port=3000
      - traefik.http.routers.tabletoptales_rt.tls=true
      - traefik.http.routers.tabletoptales_rt.tls.certresolver=myresolver
      - traefik.http.routers.tabletoptales_rt.rule=Host(`tales.thurnaround.de`)
      - traefik.http.routers.tabletoptales_rt.service=tabletoptales_svc
      - traefik.http.routers.tabletoptales_rt.entrypoints=websecure
      - traefik.docker.network=traefik
      mode: replicated
      replicas: 1

networks:
  traefik:
    external: true
